# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e3771d37aa3b6e20b6ede002d985d5e38b12a008d02f41fa50844981e2e4a1f6c04c77b547c162cceee42697ba61f755085f03bbade400478cacb7a2c3b231a

test:
  secret_key_base: fea1ed32916346798d73537ccba2b87e0e2e0777e2fef0c5664a5720e0367af22d31b9558a2aa3021aaf93e6a98e8452d0810bca6c248360f08d2970b0c5281e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
